### ISSUE TITLE
Guides

### ISSUE THREAD

**Issue by dherman** [dherman/neon-site-redesign#5]
We should start a series of _guides_ in our documentation, which are tutorials on more targeted, specific scenarios that people will commonly encounter. Here's an initial list, which we can iterate on and then turn into a checklist linking to separate issues.

- Getting Started in Windows
- Getting Started in Unix (Linux, macOS)
- Hello world
- Getting Started with Electron
- Creating Native Classes
- Handling Errors
- Using Threads

**Comment by jedireza** [comment]
- Debugging; gdb/lldb (see #3)

**Comment by dherman** [comment]
Created the [neon-bindings/guides](/neon-bindings/guides) repo and published as [guides.neon-bindings.com](https://guides.neon-bindings.com), with placeholders for each of these topics.
